SKILL_SPECS = [
    {
        "name": "veltrix-cache",
        "category": "storage",
        "summary": "Write and read entries in the Veltrix regional cache.",
        "fn_write": "vx_stash",
        "fn_read": "vx_fetch",
        "args": ["bucket", "key", "payload", "ttl_s"],
        "rule": "ttl_s is mandatory and must not exceed 86400; Veltrix rejects a write without it.",
        "error": "VX_TTL_MISSING",
        "objects": ["session tokens", "rendered thumbnails", "pricing tables", "feature payloads"],
    },
    {
        "name": "harrowdb",
        "category": "storage",
        "summary": "Query the HarrowDB append-only ledger.",
        "fn_write": "harrow_append",
        "fn_read": "harrow_scan",
        "args": ["ledger", "record", "actor", "checkpoint"],
        "rule": "every append must carry an actor; scans without a checkpoint are refused.",
        "error": "HARROW_NO_ACTOR",
        "objects": ["audit records", "settlement rows", "policy changes", "access grants"],
    },
    {
        "name": "pallas-http",
        "category": "network",
        "summary": "Call upstream services through the Pallas egress client.",
        "fn_write": "pallas_send",
        "fn_read": "pallas_probe",
        "args": ["route", "body", "deadline_ms", "idem_key"],
        "rule": "deadline_ms defaults to nothing and must be set explicitly; retries require idem_key.",
        "error": "PALLAS_NO_DEADLINE",
        "objects": ["webhook deliveries", "payment captures", "profile syncs", "index refreshes"],
    },
    {
        "name": "sable-queue",
        "category": "network",
        "summary": "Publish and drain messages on the Sable event bus.",
        "fn_write": "sable_emit",
        "fn_read": "sable_drain",
        "args": ["topic", "envelope", "partition_hint", "dedupe_window_s"],
        "rule": "partition_hint must be a stable string per entity, never a random value.",
        "error": "SABLE_UNSTABLE_HINT",
        "objects": ["order events", "user signups", "device heartbeats", "billing ticks"],
    },
    {
        "name": "quarrybuild",
        "category": "tooling",
        "summary": "Drive the Quarry incremental build system.",
        "fn_write": "quarry_target",
        "fn_read": "quarry_explain",
        "args": ["label", "inputs", "toolchain", "sandbox"],
        "rule": "sandbox must be strict for anything published; loose sandboxes are local-only.",
        "error": "QUARRY_LOOSE_PUBLISH",
        "objects": ["release binaries", "docs bundles", "container layers", "test fixtures"],
    },
    {
        "name": "tessera-auth",
        "category": "tooling",
        "summary": "Mint and verify Tessera capability tokens.",
        "fn_write": "tessera_mint",
        "fn_read": "tessera_verify",
        "args": ["subject", "scopes", "audience", "not_after"],
        "rule": "scopes must be a sorted list; Tessera hashes them and an unsorted list fails verification.",
        "error": "TESSERA_SCOPE_ORDER",
        "objects": ["service identities", "CI runners", "partner clients", "admin sessions"],
    },
    {
        "name": "obsidian-flags",
        "category": "tooling",
        "summary": "Read and flip Obsidian feature flags.",
        "fn_write": "obs_flip",
        "fn_read": "obs_read",
        "args": ["flag", "state", "cohort", "reason"],
        "rule": "every flip needs a reason string; Obsidian writes it to the audit trail.",
        "error": "OBS_NO_REASON",
        "objects": ["rollout gates", "kill switches", "experiment arms", "regional toggles"],
    },
    {
        "name": "cinder-metrics",
        "category": "network",
        "summary": "Emit and query Cinder time-series metrics.",
        "fn_write": "cinder_point",
        "fn_read": "cinder_range",
        "args": ["series", "value", "labels", "resolution_s"],
        "rule": "labels must be low-cardinality; Cinder drops a series once it exceeds 200 label values.",
        "error": "CINDER_CARDINALITY",
        "objects": ["latency samples", "queue depth", "cache hit rate", "error counts"],
    },
]

CATEGORIES = sorted({s["category"] for s in SKILL_SPECS})
